#!/usr/bin/env bash
# This script sets up necessary directories/permissions that have changed in the app since the initial release. 

set -euo pipefail

# Set a new APP_DATA_DIR, checking if the preferred location exists
if [ -d "/home/umbrel/umbrel/external/BigBoy" ]; then
    APP_DATA_DIR="/home/umbrel/umbrel/external/BigBoy"
else
    APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)/data"
fi

echo "Using APP_DATA_DIR: $APP_DATA_DIR"

# Create model-cache directory if it doesn't exist
MODEL_CACHE_DIR="${APP_DATA_DIR}/model-cache"
[ ! -d "${MODEL_CACHE_DIR}" ] && mkdir -p "${MODEL_CACHE_DIR}" && chown 1000:1000 "${MODEL_CACHE_DIR}"

# Delete tsdata directory if it exists
TYPESENSE_DIR="${APP_DATA_DIR}/tsdata"
[ -d "${TYPESENSE_DIR}" ] && rm -rf "${TYPESENSE_DIR}"

# Delete old post-update script if it exists
POST_UPDATE_SCRIPT="$(readlink -f $(dirname "${BASH_SOURCE[0]}"))/post-update"
[ -f "${POST_UPDATE_SCRIPT}" ] && rm -f "${POST_UPDATE_SCRIPT}"
