version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: cobalt_web_1
      APP_PORT: 9001
      PROXY_AUTH_ADD: "false"
  web:
    image: ghcr.io/imputnet/cobalt:10
    init: true
    read_only: true
    restart: on-failure
    ports:
      - 0.0.0.0:9000:9000
    environment:
      API_URL: "http://umbrel.local:9000/"
      API_AUTH_REQUIRED: 0
      DURATION_LIMIT: 86400
      # Uncomment the next line if you want to use cookies
      # COOKIE_PATH: "/cookies.json"
    volumes:
      - ${APP_DATA_DIR}/data/cookies/cookies.json:/cookies.json
      # Add more volume mounts here if needed