services:
  app_proxy:
    environment:
      APP_HOST: newedia-cobalt_web_1
      APP_PORT: 9009
      PROXY_AUTH_ADD: "false"
  web:
    image: ghcr.io/imputnet/cobalt:10@sha256:cf5112f71ce6b333423e09e9ac731155f04f1d75f97378227a9da28ae014447d
    init: true
    read_only: true
    restart: on-failure
    ports:
      - 0.0.0.0:9001:9001
    environment:
      API_URL: "http://umbrel.local:9001/"
      API_AUTH_REQUIRED: 0
      DURATION_LIMIT: 86400
    volumes:
      - ${APP_DATA_DIR}/data/cookies/cookies.json:/cookies.json