services:
    newedia-cobalt-api:
        image: ghcr.io/imputnet/cobalt:10
        init: true
        read_only: true
        restart: unless-stopped
        container_name: newedia-cobalt-api

        ports:
            - 0.0.0.0:9000:9000

        environment:
            API_URL: "http://localhost:9000"
            COOKIE_PATH: "/cookies.json"

        volumes:
            - ./cookies.json:/cookies.json