version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: cobalt-api
      APP_PORT: 9000
      PROXY_AUTH_ADD: "false"
  
  cobalt-api:
    image: ghcr.io/imputnet/cobalt:10
    init: true
    read_only: true
    restart: unless-stopped
    container_name: cobalt-api
    ports:
      - 4000:9000/tcp
    environment:
      # Set to your Umbrel's URL with the port we're exposing
      API_URL: "http://umbrel.local:4000/"
      API_AUTH_REQUIRED: 0
      DURATION_LIMIT: 86400
      # Uncomment the next line if you want to use cookies
      # COOKIE_PATH: "/cookies.json"
    volumes:
      - ${APP_DATA_DIR}/data/cookies/cookies.json:/cookies.json