services:
  app_proxy:
    environment:
      APP_HOST: cobalt-api
      APP_PORT: 9000
      PROXY_AUTH_ADD: "false"
  cobalt-api:
    image: ghcr.io/imputnet/cobalt:10@sha256:cf5112f71ce6b333423e09e9ac731155f04f1d75f97378227a9da28ae014447d
    init: true
    read_only: true
    restart: unless-stopped  # Updated for robustness
    container_name: cobalt-api
    ports:
      - 0.0.0.0:6578:9000
    environment:
      API_URL: "http://umbrel.local:6578/"  # Adjust if external access is needed
      API_AUTH_REQUIRED: 0
      DURATION_LIMIT: 86400
      # Uncomment if using cookies
      # COOKIE_PATH: "/cookies.json"
    volumes:
      # Uncomment if using cookies
      # - ${APP_DATA_DIR}/data/cookies/cookies.json:/cookies.json