services:
  app_proxy:
    environment:
      APP_HOST: newedia_redlib_web_1
      APP_PORT: 8080
  
  web:
    image: quay.io/redlib/redlib:latest
    restart: always
    ports:
      - 8080:8080
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - redlib
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 5m
      timeout: 3

networks:
  redlib:

      
      
